### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by netrunnernumber37** [Pandarix/Beautify#15]
I would love to play this on my 1.20 world, would you grant me permission to use the source code to port it myself?

**Comment by Takaska** [comment]
Beautify is licensed under MIT here:
https://github.com/Pandarix/Beautify/blob/main/LICENSE

Meaning you are free to port it to 1.20.1 with credit as outlined (I've seen someone do it on Fabric, but I use CurseForge). I came here looking to see if 1.20.1 was being worked on, but it looks a tad abandoned... if you do upgrade it to the newest release, I'm sure a lot of folks not on Fabric would appreciate it! (Myself included)

**Comment by netrunnernumber37** [comment]
I will work on it for sure.

**Comment by Pandarix** [comment]
I was really occupied the last few weeks.
The mod was written quite bad because it was my first.
I wanted to work on it myself and make it from the ground up and better this time if that's okay for you.
I think I'll be able to work on it very soon if you're okay with that

**Comment by Takaska** [comment]
> I was really occupied the last few weeks. The mod was written quite bad because it was my first. I wanted to work on it myself and make it from the ground up and better this time. I think I'll be able to work on it very soon if you're okay with that

All is well- I know life goes on for everyone! It would be awesome if you continued your own work of course, it's half of what has me sticking to 1.19.2 for my creative builds haha
No need to rush if there's a lot of work that needs to be done- my comment wasn't made to spite you in any way, just to provide an answer to someone a bit more knowledgeable than me in the coding department; in case you wouldn't have time/ energy to work on it! I wish you the best ^.^

**Comment by netrunnernumber37** [comment]
I can wait, I only changed the forgegraddle version and stuff, didn't get very far.

**Comment by Pandarix** [comment]
I'm on it now, shouldn't be that much of a headache. I've already deleted so much junk xD.
I'll keep you updated.

**Comment by Pandarix** [comment]
Going great, I think I'm almost ready to ship it!
`774 changed files with 3,123 additions and 3,458 deletions.` btw 👀

**Comment by Pandarix** [comment]
I'll definitely de-hardcode the translation soon.
Also, I'm thinking about cherry blossom stuff :3

**Comment by netrunnernumber37** [comment]
awesome!

**Comment by Pandarix** [comment]
It should be available with [this link](https://legacy.curseforge.com/minecraft/mc-mods/beautify-decorate/files/4692750) once it has passed the review.
Could you then please test if everything works fine? A second pair of eyes would be useful. If everything is smooth, I'd close this issue :)

**Comment by Pandarix** [comment]
Seems to be working with no issues at all. I'm gonna close this for now
