### ISSUE TITLE
Beautify crash when blinds explode

### ISSUE THREAD

**Issue by Murph2** [Pandarix/Beautify#18]
Simple crash, blow up blinds to reproduce, either via creeper or tnt. Here is the log on 1.20.1
[crash-2023-10-29_05.24.29-server.txt](https://github.com/Pandarix/Beautify/files/13198188/crash-2023-10-29_05.24.29-server.txt)

**Comment by Pandarix** [comment]
Please refer to [suel_ki's issue page](https://github.com/Suel-ki/Beautify-Refabricated/issues). This is the issues page for Beautify for Forge :)
