### ISSUE TITLE
[Bug] The botanist zombie villager doesn't have a valid skin

### ISSUE THREAD

**Issue by anzai249** [Pandarix/Beautify#21]
### Version

- Beautify 2.0.0
- Minecraft 1.20.1
- NeoForge 47.1.81

### How to trigger

Wait until night, the weird botanist zombie villager will spawn naturally. And you can use zombie villager spawn eggs to spawn it.

### Image: 
![image](https://github.com/Pandarix/Beautify/assets/32564494/7fe9f16b-6f97-4ead-b848-18d894d99360)

**Comment by Pandarix** [comment]
Sorry, this issue was fixed a while ago but I forgot to close it.
