### ISSUE TITLE
Creeper causes crash when exploding blinds

### ISSUE THREAD

**Issue by x-464** [Pandarix/Beautify#27]
A creeper that explodes near blinds causes the game to crash, I assume this is becuase of the unique way blinds work. It happens when blinds are down or up and I tested it with only beautifys nessasary mods and it still happens.
Pastebin has the crash log in it:
https://pastebin.com/PGkAy93b

Edit:
Upon further testing, even with "open from roots" set to false in configs it still happens.

**Comment by Suel-ki** [comment]
This issue only happens in fabric and is not related to forge, it will be fixed in the next release.
