### ISSUE TITLE
An error with the botanist

### ISSUE THREAD

**Issue by noirtakumi** [Pandarix/Beautify#6]
Hello! 

Ive been using your mod for quite some time now and its amazing!

i recently update the mod and i got hit by this error when running my server

[Botanist Error.txt](https://github.com/Pandarix/Beautify/files/9499983/Botanist.Error.txt)

hoping for a fix

keep up the good work!

**Comment by Pandarix** [comment]
Thanks a lot for the praise ^^'!

That's bad :(, I'll try to fix it asap, what Version of Forge are you using and did you try to run the mod alone?

**Comment by noirtakumi** [comment]
dont mention it!

I was using Forge 43.1.3 

i tested running it alone and it gave the same error

**Comment by Pandarix** [comment]
Ok, so I'm trying things out right now but haven't gotten the issue on my side yet.
Is it the same for singleplayer worlds for you?

**Comment by noirtakumi** [comment]
Thank you so much for such a quick response!
Everything works now!

Also, dont worry about it, we all have these moments!

Again, Thank you so much for such a quick fix!

**Comment by Pandarix** [comment]
No problem :), that's my responsibility - my fuckup after all xD
I'm glad that everything is fine now ^^, I hope you'll keep enjoying the mod!
Also thank you again for reporting and keeping in touch!
